runtime: custom
env: flex

env_variables:
  DB_HOST: "team15-microservice-catalog:us-west1:team15-postgres"
  DB_PORT: "5432"
  DB_USER: "team15"
  DB_PASSWORD: "team15"
  DB_NAME: "team15"
  REDIS_HOST: "10.147.183.27"
  REDIS_PORT: "6379"

beta_settings:
  cloud_sql_instances: team15-microservice-catalog:us-west1:team15-postgres

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

network:
  name: default
