services:
  postgres:
    image: postgres:15
    container_name: team15-postgres
    environment:
      POSTGRES_USER: team15
      POSTGRES_PASSWORD: team15
      POSTGRES_DB: team15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: team15-backend
    ports:
      - "50051:50051"
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=team15
      - DB_PASSWORD=team15
      - DB_NAME=team15

  envoy:
    image: envoyproxy/envoy:v1.26.1
    container_name: team15-envoy
    ports:
      - "8084:8084"
    volumes:
      - ./deploy/envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - backend

volumes:
  pgdata:
    driver: local