services:
  postgres:
    image: postgres:15
    container_name: team15-postgres
    environment:
      POSTGRES_USER: team15
      POSTGRES_PASSWORD: team15
      POSTGRES_DB: team15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: team15-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: team15-backend
    ports:
      - "8080:8080"  # Envoy will listen on 8080
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=team15
      - DB_PASSWORD=team15
      - DB_NAME=team15
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local