name: Build and Deploy to App Engine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: team15-microservice-catalog
  GAE_INSTANCE: team15-microservice-catalog
  GAE_SERVICE: default

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache-dependency-path: backend/go.sum

    - name: Install backend dependencies
      run: |
        cd backend
        go mod download

    - name: Build backend
      run: |
        cd backend
        go build ./cmd/server

  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml \
          --project=${{ env.PROJECT_ID }} \
          --version=v${{ github.run_number }} \
          --promote \
          --quiet

    - name: Test deployment
      run: |
        # Wait for deployment to be ready
        sleep 30
        
        # Test login endpoint
        curl -f -X POST https://${{ env.GAE_INSTANCE }}.uw.r.appspot.com/login \
          -H "Content-Type: application/json" \
          -d '{"username":"admin","password":"secret"}' || exit 1
        
        echo "✅ Backend API is responding correctly!"

    - name: Notify on success
      if: success()
      run: |
        echo "✅ Deployment successful!"
        echo "🌐 Application URL: https://${{ env.GAE_INSTANCE }}.uw.r.appspot.com"

    - name: Notify on failure
      if: failure()
      run: |
        echo "❌ Deployment failed!"
        exit 1
